spring.application.name=ratelimiter

#serv config
server.port=8080

#rate limiter config
ratelimiter.default.requests-per-window=10
ratelimiter.default.window-seconds=60
ratelimiter.default.algorithm=FIXED_WINDOW

#logging
logging.level.com.rjv.ratelimiter=DEBUG
logging.level.org.springframework.web=INFO