spring.application.name=ratelimiter

#serv config
server.port=8080

#rate limiter config
ratelimiter.default.requests-per-window=10
ratelimiter.default.window-seconds=60

#algo selection, test
ratelimiter.default.algorithm=FIXED_WINDOW

#logging
logging.level.com.rjv.ratelimiter=DEBUG
logging.level.org.springframework.web=INFO

#use redis storage
ratelimiter.storage.type=redis

# actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

# redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=500ms
spring.data.redis.lettuce.shutdown-timeout=0ms

# connection validation
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.test-on-borrow=true